version: "3"

services:
  db:
    image: mariadb:latest
    command:
      [
        "--character-set-server=utf8",
        "--collation-server=utf8_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    restart: always
    environment:
      MYSQL_DATABASE: pano
      MYSQL_ROOT_PASSWORD: pano
    ports:
      - "3306:3306"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
