version: '3'
services:
  db:
    image: mysql:5.7
    command: ["--character-set-server=utf8", "--collation-server=utf8_unicode_ci" ,"--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      MYSQL_DATABASE: pano
      MYSQL_ROOT_PASSWORD: pano
    ports:
      - "3306:3306"
